### ISSUE TITLE
Missing opencv_arucod411.lib When I build the ComputeOnDesktopYolo project 

### ISSUE THREAD

**Issue by NelsonHou** [doughtmw/YoloDetectionHoloLens-Unity#1]

**Comment by doughtmw** [comment]
Thanks! The NuGet package that was referenced in the `HoloLensForCV` project was outdated. I [updated the reference to the Nuget package submodule](https://github.com/doughtmw/YoloDetectionHoloLens-Unity/commit/74d22bf6d8ea56fcd88c50a4ea95fde396d9e671) so it should work now.
