### ISSUE TITLE
Use my own model

### ISSUE THREAD

**Issue by Hellstormer00** [doughtmw/YoloDetectionHoloLens-Unity#10]
Hello,

I was wondering how to change the weights of the yolo model and use my own model

Thanks

**Comment by doughtmw** [comment]
Hi @Hellstormer00! Provided you are using a similar YOLO style framework, you would need to convert your trained model weights from whichever format you trained in (Tensorflow, PyTorch, etc.) to an ONNX model format. After conversion to ONNX format, make sure you check that your model structure and weights are correct and give results consistent with your original trained model. There are some helpful examples and tools for ONNX conversion at in the [MSFT repo](https://github.com/microsoft/Windows-Machine-Learning).

**Comment by doughtmw** [comment]
You can also take a look at [this repo of mine](https://github.com/doughtmw/HoloLens2-Machine-Learning) which may be a bit clearer to understand how ONNX models are used on the HoloLens for inference.

**Comment by Hellstormer00** [comment]
Thank you very much
