### ISSUE TITLE
Error when deploying the ComputeOnDesktopYolo project

### ISSUE THREAD

**Issue by utrav** [doughtmw/YoloDetectionHoloLens-Unity#2]
Hello Mitchell, when I deploy the ComputeOnDesktopYolo project on Local Machine, I get the error:

Exception thrown at 0x09546B00 in ComputeOnDesktopYolo.exe: 0xC0000005: Access violation executing location 0x09546B00.

Can you please help me understand what went wrong?
Thank you!

EDIT: I have noticed that the exception occurs when the function concurrency::task<void> MainPage::LoadModelAsync() is called, even if it is called with its content commented. Any ideas why this function causes this exception?

**Comment by utrav** [comment]
For anyone having the same problem, I got it fixed by changing the MainPage.xaml.cpp of ComputeOnDesktopYolo. More specifically, I commented line 42 (LoadModelAsync();) and copied content from LoadModelAsync() in MainPage() initialization, like this:

```
	MainPage::MainPage()
	{
		InitializeComponent();

		try
		{
			String^ filePath = "ms-appx:///Assets/" + modelFileName;

			// From Windows ML samples, MNIST cpp
			create_task(StorageFile::GetFileFromApplicationUriAsync(
				ref new Uri(filePath)))
				.then([](StorageFile^ modelFile) {
				return create_task(YoloModelIO::Model::CreateFromStreamAsync(
					modelFile,
					LearningModelDeviceKind::Default)); })
				.then([this](YoloModelIO::Model ^model) {
					this->_model = model;
				});
		}
		catch (const std::exception&)
		{
			std::wstringstream wStringstream2;
			wStringstream2 << "Error loading the model." << "\n";
			OutputDebugString(wStringstream2.str().c_str());
			_model = nullptr;
		}
	}
```

**Comment by xgjhlws** [comment]
Maybe just need to choose “Release x64”. I got the same error when I chose "Debug x64".
