### ISSUE TITLE
Does this work with HL2?

### ISSUE THREAD

**Issue by jtrinidad6** [doughtmw/YoloDetectionHoloLens-Unity#3]

**Comment by rooi** [comment]
Thanks for sharing @doughtmw!

I just tried on HL2 and the server and client do seem to connect (messages in debugger). However, the camera on the HL2 is not enabled and the video is not stream to the desktop application. All capabilities seem correct and I've managed to get your Aruco example and the Unity openCV example by EnoxSoftware working.

Am I doing something wrong or is the example nog fully compatible with HL2?

Thanks!

Roy

**Comment by doughtmw** [comment]
Hi Roy! Thanks for your comment. I've updated the repo to support HL2 media frame source group streaming (as in the ArUco sample). I also added prebuilt project binaries for ARM configuration builds. Let me know if you're able to get the sample working now!

**Comment by rooi** [comment]
Thanks Mitchell!

The HL2 is now able to stream video to ComputeOnDesktopYolo and Yolo detection works on the desktop and draws bounding boxes. However, these are not visible on the HL and after some time (30 seconds), the connection is closed:

ComputeOnDesktopYolo
"An existing connection was forcibly closed by the remote host.
WinRT information: An existing connection was forcibly closed by the remote host."  

I did not manage to fully debug this yet, but I will try to do so early next week.

Have you seen the HoloLens2ForCV released today by the way?

Roy

**Comment by rooi** [comment]
Ah I did not set the correct ip adress in Unity. Now it connects and sends data. The bounding boxes sizes and positions are still 0, but this is probably something small.

Thx!
