### ISSUE TITLE
OpenCV.HoloLens.3411.0.0.nupkg How to install

### ISSUE THREAD

**Issue by RenSiyao** [doughtmw/YoloDetectionHoloLens-Unity#4]
According to the installation method mentioned in the article：
Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg -ProjectName ComputeOnDesktopYolo
Install-Package ..\OpenCV.HoloLens.3411.0.0.nupkg -ProjectName OpenCVHelpers
I entered the above command in the program envelope console of the project as follows：
![image](https://user-images.githubusercontent.com/53859046/93447396-f000ef80-f904-11ea-9d7a-6dc9741c40f7.png)
Could you point out the problem to me?

**Comment by NHarishGit** [comment]
I have the same issue, any resolve ?

**Comment by xgjhlws** [comment]
![image](https://user-images.githubusercontent.com/19727851/97803157-2ad7a080-1c83-11eb-833b-7d419272bfad.png)


1-2-3-4，set the source，the path is where your file "OpenCV.HoloLens.3411.0.0.nupkg" exist
Then click the "restore" at 5
