### ISSUE TITLE
Can't recieve boundingboxes on HL1

### ISSUE THREAD

**Issue by MaxDagerbratt** [doughtmw/YoloDetectionHoloLens-Unity#5]
Hi,

I've got everything working except receiving the bounding boxes on the HoloLens.
I can see the bounding boxes on the desktop client but if I double-click in the HoloLens app the text "No bounding boxes received" shows and then the app crashed within 10-20 seconds with the following error in VS:

Exception thrown at 0x76C03A12 in YoloDetectionHoloLensUnity.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x0717FA10. HRESULT:0x8007274C A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
WinRT information: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
 
I have no idea what could cause this. I've tested it with the devices on the same WIFI and with the desktop being connected through cable (Changed IP in Unity when switching from/to cable).

Does anyone know what could cause this or what a solution could be?

**Comment by Hellstormer00** [comment]
Hello did you find a solution on this issue? I currently have the same one with HL2

**Comment by As-Zach** [comment]
+1
